################ Marloes test with ground truths ###############################3
# Healthy subset 1 met ground truths
python Machine-learning-driven-Heckmatt-grading-in-facioscapulohumeral-muscular-dystrophy/mmsegmentation/tools/local_inference.py /home/marloes.stemerdink@mydre.org/Documents/analysis/Machine-learning-driven-Heckmatt-grading-in-facioscapulohumeral-muscular-dystrophy/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f0_binary.py --checkpoint /mnt/data/trained_models/FSHD_binary_models/FSHD_binary_models/FSHD_config_SWIN_f0_binary.pth --img_folder /mnt/data/dataset_training/subset_1/healthy/converted_png/images/ --out_results /mnt/data/dataset_training/subset_1/results/healthy/ --ground_truth /mnt/data/dataset_training/subset_1/healthy/converted_png/masks/ --plot_rgb --plot_label_compare



################ DP_GAN

python tools/local_inference.py /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidB/Thyroid_B.py --checkpoint /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidB/iter_40000.pth --img_folder /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/results/dp_gan_thyroid_B_512_v0/0/image --out_results /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/checkpoints/dp_gan_thyroid_B_512_v0/segmentation/iter_0 --ground_truth /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/datasets/B_768/validation/seg_maps_512 --plot_rgb --plot_label_compare
python tools/local_inference.py /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidB/Thyroid_B.py --checkpoint /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidB/iter_40000.pth --img_folder /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/results/dp_gan_thyroid_B_512_v0/5000/image --out_results /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/checkpoints/dp_gan_thyroid_B_512_v0/segmentation/iter_5000 --ground_truth /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/datasets/B_768/validation/seg_maps_512 --plot_rgb --plot_label_compare
python tools/local_inference.py /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidB/Thyroid_B.py --checkpoint /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidB/iter_40000.pth --img_folder /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/results/dp_gan_thyroid_B_512_v0/10000/image --out_results /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/checkpoints/dp_gan_thyroid_B_512_v0/segmentation/iter_10000 --ground_truth /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/datasets/B_768/validation/seg_maps_512 --plot_rgb --plot_label_compare
python tools/local_inference.py /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidB/Thyroid_B.py --checkpoint /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidB/iter_40000.pth --img_folder /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/results/dp_gan_thyroid_B_512_v0/15000/image --out_results /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/checkpoints/dp_gan_thyroid_B_512_v0/segmentation/iter_15000 --ground_truth /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/datasets/B_768/validation/seg_maps_512 --plot_rgb --plot_label_compare
python tools/local_inference.py /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidB/Thyroid_B.py --checkpoint /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidB/iter_40000.pth --img_folder /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/results/dp_gan_thyroid_B_512_v0/20000/image --out_results /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/checkpoints/dp_gan_thyroid_B_512_v0/segmentation/iter_20000 --ground_truth /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/datasets/B_768/validation/seg_maps_512 --plot_rgb --plot_label_compare
python tools/local_inference.py /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidB/Thyroid_B.py --checkpoint /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidB/iter_40000.pth --img_folder /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/results/dp_gan_thyroid_B_512_v0/25000/image --out_results /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/checkpoints/dp_gan_thyroid_B_512_v0/segmentation/iter_25000 --ground_truth /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/datasets/B_768/validation/seg_maps_512 --plot_rgb --plot_label_compare
python tools/local_inference.py /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidB/Thyroid_B.py --checkpoint /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidB/iter_40000.pth --img_folder /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/results/dp_gan_thyroid_B_512_v0/30000/image --out_results /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/checkpoints/dp_gan_thyroid_B_512_v0/segmentation/iter_30000 --ground_truth /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/datasets/B_768/validation/seg_maps_512 --plot_rgb --plot_label_compare
python tools/local_inference.py /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidB/Thyroid_B.py --checkpoint /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidB/iter_40000.pth --img_folder /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/results/dp_gan_thyroid_B_512_v0/35000/image --out_results /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/checkpoints/dp_gan_thyroid_B_512_v0/segmentation/iter_35000 --ground_truth /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/datasets/B_768/validation/seg_maps_512 --plot_rgb --plot_label_compare
python tools/local_inference.py /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidB/Thyroid_B.py --checkpoint /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidB/iter_40000.pth --img_folder /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/results/dp_gan_thyroid_B_512_v0/40000/image --out_results /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/checkpoints/dp_gan_thyroid_B_512_v0/segmentation/iter_40000 --ground_truth /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/datasets/B_768/validation/seg_maps_512 --plot_rgb --plot_label_compare
python tools/local_inference.py /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidB/Thyroid_B.py --checkpoint /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidB/iter_40000.pth --img_folder /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/results/dp_gan_thyroid_B_512_v0/45000/image --out_results /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/checkpoints/dp_gan_thyroid_B_512_v0/segmentation/iter_45000 --ground_truth /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/datasets/B_768/validation/seg_maps_512 --plot_rgb --plot_label_compare
python tools/local_inference.py /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidB/Thyroid_B.py --checkpoint /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidB/iter_40000.pth --img_folder /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/results/dp_gan_thyroid_B_512_v0/50000/image --out_results /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/checkpoints/dp_gan_thyroid_B_512_v0/segmentation/iter_50000 --ground_truth /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/datasets/B_768/validation/seg_maps_512 --plot_rgb --plot_label_compare
python tools/local_inference.py /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidB/Thyroid_B.py --checkpoint /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidB/iter_40000.pth --img_folder /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/results/dp_gan_thyroid_B_512_v0/55000/image --out_results /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/checkpoints/dp_gan_thyroid_B_512_v0/segmentation/iter_55000 --ground_truth /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/datasets/B_768/validation/seg_maps_512 --plot_rgb --plot_label_compare
python tools/local_inference.py /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidB/Thyroid_B.py --checkpoint /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidB/iter_40000.pth --img_folder /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/results/dp_gan_thyroid_B_512_v0/60000/image --out_results /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/checkpoints/dp_gan_thyroid_B_512_v0/segmentation/iter_60000 --ground_truth /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/datasets/B_768/validation/seg_maps_512 --plot_rgb --plot_label_compare
python tools/local_inference.py /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidB/Thyroid_B.py --checkpoint /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidB/iter_40000.pth --img_folder /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/results/dp_gan_thyroid_B_512_v0/65000/image --out_results /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/checkpoints/dp_gan_thyroid_B_512_v0/segmentation/iter_65000 --ground_truth /media/francesco/DEV001/PROJECT-KERNEL/DP_GAN/datasets/B_768/validation/seg_maps_512 --plot_rgb --plot_label_compare

############## THYROID A ###########################

python local_inference.py /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidA/Thyroid_A.py --checkpoint /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidA/iter_24000.pth --img_folder /media/francesco/DEV001/PROJECT-THYROID/CODE/mmsegmentation/data/thyroid_A/img_dir/test --out_results /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidA/TEST --ground_truth /media/francesco/DEV001/PROJECT-THYROID/CODE/mmsegmentation/data/thyroid_A/ann_dir/test --plot_rgb --plot_label_compare

############## THYROID B ###########################

python local_inference.py /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidB/Thyroid_B.py --checkpoint /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidB/iter_24000.pth --img_folder /media/francesco/DEV001/PROJECT-THYROID/CODE/mmsegmentation/data/thyroid_B/img_dir/test --out_results /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidB/TEST --ground_truth /media/francesco/DEV001/PROJECT-THYROID/CODE/mmsegmentation/data/thyroid_B/ann_dir/test --plot_rgb --plot_label_compare
python local_inference.py /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidB/Thyroid_B.py --checkpoint /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidB/iter_40000.pth --img_folder /media/francesco/DEV001/PROJECT-THYROID/DATA/ORIGINAL/LINDA/Thyroid_Images_01052024 --out_results /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidB/TEST  --plot_rgb

############## GALLO ###########################

python local_inference.py /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidB/Thyroid_B.py --checkpoint /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/ThyroidB/iter_40000.pth --img_folder /media/francesco/DEV001/PROJECT-THYROID/DATA/GALLO/Images --out_results /media/francesco/DEV001/PROJECT-THYROID/RESULTS/Gallo/ --ground_truth /media/francesco/DEV001/PROJECT-THYROID/DATA/GALLO/Masks --plot_rgb --plot_label_compare

############## DERMA ###########################

python ./tools/local_inference.py /media/francesco/DEV001/PROJECT-THYROID/CODE/mmsegmentation/configs/DERMA_experiments/DERMA_config.py --checkpoint /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/DERMA/iter_16000.pth --img_folder /media/francesco/DEV001/PROJECT-THYROID/CODE/mmsegmentation/data/DERMA/img_dir/test --out_results /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/DERMA/out_test --ground_truth /media/francesco/DEV001/PROJECT-THYROID/CODE/mmsegmentation/data/DERMA/ann_dir/test --plot_rgb --plot_label_compare
python ./tools/local_inference.py /media/francesco/DEV001/PROJECT-THYROID/CODE/mmsegmentation/configs/DERMA_experiments/DERMA_config.py --checkpoint /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/DERMA/iter_40000.pth --img_folder /media/francesco/DEV001/PROJECT-THYROID/CODE/mmsegmentation/data/SelectedHQ --out_results /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/DERMA/out_HQ_res_40k --plot_rgb


############## MINERVINO ###########################

python local_inference.py /media/francesco/DEV001/PROJECT-THYROID/CODE/mmsegmentation/configs/IMT_experiments/IMT.py --checkpoint /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/IMT/iter_40000.pth --img_folder /media/francesco/DEV001/DIDATTICA/TESI/ACTIVE-MINERVINO-CUBS-SYNTH/SDM --out_results /media/francesco/DEV001/DIDATTICA/TESI/ACTIVE-MINERVINO-CUBS-SYNTH/Results_SDM --ground_truth /media/francesco/DEV001/PROJECT-THYROID/DATA/IMT/LABELS --plot_rgb --plot_label_compare
python local_inference.py /media/francesco/DEV001/PROJECT-THYROID/CODE/mmsegmentation/configs/IMT_experiments/IMT.py --checkpoint /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/IMT/iter_40000.pth --img_folder /media/francesco/DEV001/DIDATTICA/TESI/ACTIVE-MINERVINO-CUBS-SYNTH/SPADE --out_results /media/francesco/DEV001/DIDATTICA/TESI/ACTIVE-MINERVINO-CUBS-SYNTH/Results_SPADE --ground_truth /media/francesco/DEV001/PROJECT-THYROID/DATA/IMT/LABELS --plot_rgb --plot_label_compare

############## FSHD ###########################

python tools/local_inference.py /media/francesco/DEV001/PROJECT-THYROID/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f0.py --checkpoint /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/FSHD_KNET_SWIN_f0/iter_80000.pth --img_folder /media/francesco/DEV001/PROJECT-FSHD/DATA/FSHD_v3_f0/img_dir/test --out_results /media/francesco/DEV001/PROJECT-FSHD/RESULTS/SEGMENTATION/knet_v3_swin_f0 --ground_truth /media/francesco/DEV001/PROJECT-FSHD/DATA/FSHD_v3_f0/ann_dir/test --plot_rgb --plot_label_compare
python tools/local_inference.py /media/francesco/DEV001/PROJECT-THYROID/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f1.py --checkpoint /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/FSHD_KNET_SWIN_f1/iter_80000.pth --img_folder /media/francesco/DEV001/PROJECT-FSHD/DATA/FSHD_v3_f1/img_dir/test --out_results /media/francesco/DEV001/PROJECT-FSHD/RESULTS/SEGMENTATION/knet_v3_swin_f1 --ground_truth /media/francesco/DEV001/PROJECT-FSHD/DATA/FSHD_v3_f1/ann_dir/test --plot_rgb --plot_label_compare
python tools/local_inference.py /media/francesco/DEV001/PROJECT-THYROID/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f2.py --checkpoint /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/FSHD_KNET_SWIN_f2/iter_80000.pth --img_folder /media/francesco/DEV001/PROJECT-FSHD/DATA/FSHD_v3_f2/img_dir/test --out_results /media/francesco/DEV001/PROJECT-FSHD/RESULTS/SEGMENTATION/knet_v3_swin_f2 --ground_truth /media/francesco/DEV001/PROJECT-FSHD/DATA/FSHD_v3_f2/ann_dir/test --plot_rgb --plot_label_compare
python tools/local_inference.py /media/francesco/DEV001/PROJECT-THYROID/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f3.py --checkpoint /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/FSHD_KNET_SWIN_f3/iter_80000.pth --img_folder /media/francesco/DEV001/PROJECT-FSHD/DATA/FSHD_v3_f3/img_dir/test --out_results /media/francesco/DEV001/PROJECT-FSHD/RESULTS/SEGMENTATION/knet_v3_swin_f3 --ground_truth /media/francesco/DEV001/PROJECT-FSHD/DATA/FSHD_v3_f3/ann_dir/test --plot_rgb --plot_label_compare
python tools/local_inference.py /media/francesco/DEV001/PROJECT-THYROID/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f4.py --checkpoint /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/FSHD_KNET_SWIN_f4/iter_80000.pth --img_folder /media/francesco/DEV001/PROJECT-FSHD/DATA/FSHD_v3_f4/img_dir/test --out_results /media/francesco/DEV001/PROJECT-FSHD/RESULTS/SEGMENTATION/knet_v3_swin_f4 --ground_truth /media/francesco/DEV001/PROJECT-FSHD/DATA/FSHD_v3_f4/ann_dir/test --plot_rgb --plot_label_compare


############## FSHD-mod ###########################

python tools/local_inference.py /media/francesco/DEV001/PROJECT-THYROID/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f0.py --checkpoint /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/FSHD_KNET_SWIN_f0/iter_80000.pth --img_folder /media/francesco/DEV001/PROJECT-FSHD/DATA/FSHD_v3_f0/img_dir/test_mod --out_results /media/francesco/DEV001/PROJECT-FSHD/RESULTS/SEGMENTATION/knet_v3_swin_mod_f0 --ground_truth /media/francesco/DEV001/PROJECT-FSHD/DATA/FSHD_v3_f0/ann_dir/test --plot_rgb --plot_label_compare
python tools/local_inference.py /media/francesco/DEV001/PROJECT-THYROID/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f1.py --checkpoint /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/FSHD_KNET_SWIN_f1/iter_80000.pth --img_folder /media/francesco/DEV001/PROJECT-FSHD/DATA/FSHD_v3_f1/img_dir/test_mod --out_results /media/francesco/DEV001/PROJECT-FSHD/RESULTS/SEGMENTATION/knet_v3_swin_mod_f1 --ground_truth /media/francesco/DEV001/PROJECT-FSHD/DATA/FSHD_v3_f1/ann_dir/test --plot_rgb --plot_label_compare
python tools/local_inference.py /media/francesco/DEV001/PROJECT-THYROID/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f2.py --checkpoint /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/FSHD_KNET_SWIN_f2/iter_80000.pth --img_folder /media/francesco/DEV001/PROJECT-FSHD/DATA/FSHD_v3_f2/img_dir/test_mod --out_results /media/francesco/DEV001/PROJECT-FSHD/RESULTS/SEGMENTATION/knet_v3_swin_mod_f2 --ground_truth /media/francesco/DEV001/PROJECT-FSHD/DATA/FSHD_v3_f2/ann_dir/test --plot_rgb --plot_label_compare
python tools/local_inference.py /media/francesco/DEV001/PROJECT-THYROID/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f3.py --checkpoint /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/FSHD_KNET_SWIN_f3/iter_80000.pth --img_folder /media/francesco/DEV001/PROJECT-FSHD/DATA/FSHD_v3_f3/img_dir/test_mod --out_results /media/francesco/DEV001/PROJECT-FSHD/RESULTS/SEGMENTATION/knet_v3_swin_mod_f3 --ground_truth /media/francesco/DEV001/PROJECT-FSHD/DATA/FSHD_v3_f3/ann_dir/test --plot_rgb --plot_label_compare
python tools/local_inference.py /media/francesco/DEV001/PROJECT-THYROID/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f4.py --checkpoint /media/francesco/DEV001/PROJECT-THYROID/RESULTS/mmsegmentation/FSHD_KNET_SWIN_f4/iter_80000.pth --img_folder /media/francesco/DEV001/PROJECT-FSHD/DATA/FSHD_v3_f4/img_dir/test_mod --out_results /media/francesco/DEV001/PROJECT-FSHD/RESULTS/SEGMENTATION/knet_v3_swin_mod_f4 --ground_truth /media/francesco/DEV001/PROJECT-FSHD/DATA/FSHD_v3_f4/ann_dir/test --plot_rgb --plot_label_compare

############## FSHD - binary ###########################

python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f0_binary.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f0_binary/iter_80000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f0_binary/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f0_binary --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f0_binary/ann_dir/test --plot_rgb --plot_label_compare
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f1_binary.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f1_binary/iter_80000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f1_binary/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f1_binary --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f1_binary/ann_dir/test --plot_rgb --plot_label_compare   
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f2_binary.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f2_binary/iter_80000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f2_binary/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f2_binary --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f2_binary/ann_dir/test --plot_rgb --plot_label_compare
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f3_binary.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f3_binary/iter_80000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f3_binary/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f3_binary --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f3_binary/ann_dir/test --plot_rgb --plot_label_compare
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f4_binary.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f4_binary/iter_80000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f4_binary/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f4_binary --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f4_binary/ann_dir/test --plot_rgb --plot_label_compare

############## FSHD - Biceps_brachii ###########################
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f0_Biceps_brachii.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f0_Biceps_brachii/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f0_Biceps_brachii/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f0_Biceps_brachii --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f0_Biceps_brachii/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f1_Biceps_brachii.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f1_Biceps_brachii/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f1_Biceps_brachii/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f1_Biceps_brachii --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f1_Biceps_brachii/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f2_Biceps_brachii.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f2_Biceps_brachii/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f2_Biceps_brachii/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f2_Biceps_brachii --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f2_Biceps_brachii/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f3_Biceps_brachii.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f3_Biceps_brachii/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f3_Biceps_brachii/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f3_Biceps_brachii --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f3_Biceps_brachii/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f4_Biceps_brachii.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f4_Biceps_brachii/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f4_Biceps_brachii/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f4_Biceps_brachii --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f4_Biceps_brachii/ann_dir/test

############## FSHD - Deltoideus ###########################
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f0_Deltoideus.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f0_Deltoideus/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f0_Deltoideus/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f0_Deltoideus --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f0_Deltoideus/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f1_Deltoideus.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f1_Deltoideus/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f1_Deltoideus/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f1_Deltoideus --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f1_Deltoideus/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f2_Deltoideus.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f2_Deltoideus/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f2_Deltoideus/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f2_Deltoideus --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f2_Deltoideus/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f3_Deltoideus.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f3_Deltoideus/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f3_Deltoideus/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f3_Deltoideus --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f3_Deltoideus/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f4_Deltoideus.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f4_Deltoideus/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f4_Deltoideus/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f4_Deltoideus --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f4_Deltoideus/ann_dir/test

############## FSHD - Depressor_anguli_oris ###########################
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f0_Depressor_anguli_oris.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f0_Depressor_anguli_oris/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f0_Depressor_anguli_oris/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f0_Depressor_anguli_oris --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f0_Depressor_anguli_oris/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f1_Depressor_anguli_oris.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f1_Depressor_anguli_oris/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f1_Depressor_anguli_oris/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f1_Depressor_anguli_oris --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f1_Depressor_anguli_oris/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f2_Depressor_anguli_oris.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f2_Depressor_anguli_oris/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f2_Depressor_anguli_oris/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f2_Depressor_anguli_oris --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f2_Depressor_anguli_oris/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f3_Depressor_anguli_oris.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f3_Depressor_anguli_oris/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f3_Depressor_anguli_oris/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f3_Depressor_anguli_oris --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f3_Depressor_anguli_oris/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f4_Depressor_anguli_oris.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f4_Depressor_anguli_oris/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f4_Depressor_anguli_oris/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f4_Depressor_anguli_oris --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f4_Depressor_anguli_oris/ann_dir/test

############## FSHD - Digastricus ###########################
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f0_Digastricus.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f0_Digastricus/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f0_Digastricus/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f0_Digastricus --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f0_Digastricus/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f1_Digastricus.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f1_Digastricus/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f1_Digastricus/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f1_Digastricus --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f1_Digastricus/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f2_Digastricus.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f2_Digastricus/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f2_Digastricus/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f2_Digastricus --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f2_Digastricus/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f3_Digastricus.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f3_Digastricus/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f3_Digastricus/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f3_Digastricus --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f3_Digastricus/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f4_Digastricus.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f4_Digastricus/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f4_Digastricus/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f4_Digastricus --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f4_Digastricus/ann_dir/test

############## FSHD - Gastrocnemius_medial_head ###########################
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f0_Gastrocnemius_medial_head.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f0_Gastrocnemius_medial_head/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f0_Gastrocnemius_medial_head/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f0_Gastrocnemius_medial_head --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f0_Gastrocnemius_medial_head/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f1_Gastrocnemius_medial_head.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f1_Gastrocnemius_medial_head/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f1_Gastrocnemius_medial_head/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f1_Gastrocnemius_medial_head --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f1_Gastrocnemius_medial_head/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f2_Gastrocnemius_medial_head.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f2_Gastrocnemius_medial_head/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f2_Gastrocnemius_medial_head/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f2_Gastrocnemius_medial_head --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f2_Gastrocnemius_medial_head/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f3_Gastrocnemius_medial_head.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f3_Gastrocnemius_medial_head/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f3_Gastrocnemius_medial_head/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f3_Gastrocnemius_medial_head --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f3_Gastrocnemius_medial_head/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f4_Gastrocnemius_medial_head.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f4_Gastrocnemius_medial_head/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f4_Gastrocnemius_medial_head/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f4_Gastrocnemius_medial_head --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f4_Gastrocnemius_medial_head/ann_dir/test

############## FSHD - Geniohyoideus ###########################
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f0_Geniohyoideus.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f0_Geniohyoideus/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f0_Geniohyoideus/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f0_Geniohyoideus --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f0_Geniohyoideus/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f1_Geniohyoideus.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f1_Geniohyoideus/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f1_Geniohyoideus/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f1_Geniohyoideus --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f1_Geniohyoideus/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f2_Geniohyoideus.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f2_Geniohyoideus/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f2_Geniohyoideus/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f2_Geniohyoideus --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f2_Geniohyoideus/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f3_Geniohyoideus.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f3_Geniohyoideus/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f3_Geniohyoideus/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f3_Geniohyoideus --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f3_Geniohyoideus/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f4_Geniohyoideus.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f4_Geniohyoideus/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f4_Geniohyoideus/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f4_Geniohyoideus --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f4_Geniohyoideus/ann_dir/test

############## FSHD - Masseter ###########################
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f0_Masseter.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f0_Masseter/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f0_Masseter/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f0_Masseter --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f0_Masseter/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f1_Masseter.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f1_Masseter/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f1_Masseter/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f1_Masseter --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f1_Masseter/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f2_Masseter.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f2_Masseter/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f2_Masseter/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f2_Masseter --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f2_Masseter/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f3_Masseter.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f3_Masseter/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f3_Masseter/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f3_Masseter --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f3_Masseter/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f4_Masseter.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f4_Masseter/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f4_Masseter/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f4_Masseter --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f4_Masseter/ann_dir/test

############## FSHD - Mentalis ###########################
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f0_Mentalis.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f0_Mentalis/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f0_Mentalis/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f0_Mentalis --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f0_Mentalis/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f1_Mentalis.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f1_Mentalis/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f1_Mentalis/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f1_Mentalis --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f1_Mentalis/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f2_Mentalis.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f2_Mentalis/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f2_Mentalis/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f2_Mentalis --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f2_Mentalis/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f3_Mentalis.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f3_Mentalis/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f3_Mentalis/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f3_Mentalis --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f3_Mentalis/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f4_Mentalis.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f4_Mentalis/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f4_Mentalis/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f4_Mentalis --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f4_Mentalis/ann_dir/test

############## FSHD - Orbicularis_oris ###########################
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f0_Orbicularis_oris.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f0_Orbicularis_oris/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f0_Orbicularis_oris/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f0_Orbicularis_oris --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f0_Orbicularis_oris/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f1_Orbicularis_oris.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f1_Orbicularis_oris/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f1_Orbicularis_oris/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f1_Orbicularis_oris --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f1_Orbicularis_oris/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f2_Orbicularis_oris.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f2_Orbicularis_oris/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f2_Orbicularis_oris/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f2_Orbicularis_oris --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f2_Orbicularis_oris/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f3_Orbicularis_oris.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f3_Orbicularis_oris/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f3_Orbicularis_oris/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f3_Orbicularis_oris --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f3_Orbicularis_oris/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f4_Orbicularis_oris.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f4_Orbicularis_oris/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f4_Orbicularis_oris/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f4_Orbicularis_oris --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f4_Orbicularis_oris/ann_dir/test

############## FSHD - Rectus_abdominis ###########################
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f0_Rectus_abdominis.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f0_Rectus_abdominis/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f0_Rectus_abdominis/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f0_Rectus_abdominis --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f0_Rectus_abdominis/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f1_Rectus_abdominis.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f1_Rectus_abdominis/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f1_Rectus_abdominis/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f1_Rectus_abdominis --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f1_Rectus_abdominis/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f2_Rectus_abdominis.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f2_Rectus_abdominis/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f2_Rectus_abdominis/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f2_Rectus_abdominis --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f2_Rectus_abdominis/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f3_Rectus_abdominis.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f3_Rectus_abdominis/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f3_Rectus_abdominis/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f3_Rectus_abdominis --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f3_Rectus_abdominis/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f4_Rectus_abdominis.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f4_Rectus_abdominis/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f4_Rectus_abdominis/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f4_Rectus_abdominis --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f4_Rectus_abdominis/ann_dir/test

############## FSHD - Rectus_femoris ###########################
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f0_Rectus_femoris.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f0_Rectus_femoris/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f0_Rectus_femoris/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f0_Rectus_femoris --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f0_Rectus_femoris/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f1_Rectus_femoris.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f1_Rectus_femoris/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f1_Rectus_femoris/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f1_Rectus_femoris --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f1_Rectus_femoris/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f2_Rectus_femoris.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f2_Rectus_femoris/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f2_Rectus_femoris/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f2_Rectus_femoris --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f2_Rectus_femoris/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f3_Rectus_femoris.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f3_Rectus_femoris/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f3_Rectus_femoris/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f3_Rectus_femoris --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f3_Rectus_femoris/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f4_Rectus_femoris.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f4_Rectus_femoris/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f4_Rectus_femoris/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f4_Rectus_femoris --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f4_Rectus_femoris/ann_dir/test

############## FSHD - Temporalis ###########################
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f0_Temporalis.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f0_Temporalis/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f0_Temporalis/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f0_Temporalis --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f0_Temporalis/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f1_Temporalis.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f1_Temporalis/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f1_Temporalis/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f1_Temporalis --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f1_Temporalis/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f2_Temporalis.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f2_Temporalis/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f2_Temporalis/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f2_Temporalis --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f2_Temporalis/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f3_Temporalis.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f3_Temporalis/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f3_Temporalis/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f3_Temporalis --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f3_Temporalis/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f4_Temporalis.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f4_Temporalis/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f4_Temporalis/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f4_Temporalis --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f4_Temporalis/ann_dir/test

############## FSHD - Tibialis_anterior ###########################
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f0_Tibialis_anterior.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f0_Tibialis_anterior/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f0_Tibialis_anterior/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f0_Tibialis_anterior --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f0_Tibialis_anterior/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f1_Tibialis_anterior.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f1_Tibialis_anterior/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f1_Tibialis_anterior/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f1_Tibialis_anterior --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f1_Tibialis_anterior/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f2_Tibialis_anterior.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f2_Tibialis_anterior/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f2_Tibialis_anterior/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f2_Tibialis_anterior --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f2_Tibialis_anterior/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f3_Tibialis_anterior.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f3_Tibialis_anterior/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f3_Tibialis_anterior/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f3_Tibialis_anterior --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f3_Tibialis_anterior/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f4_Tibialis_anterior.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f4_Tibialis_anterior/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f4_Tibialis_anterior/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f4_Tibialis_anterior --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f4_Tibialis_anterior/ann_dir/test

############## FSHD - Trapezius ###########################
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f0_Trapezius.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f0_Trapezius/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f0_Trapezius/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f0_Trapezius --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f0_Trapezius/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f1_Trapezius.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f1_Trapezius/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f1_Trapezius/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f1_Trapezius --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f1_Trapezius/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f2_Trapezius.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f2_Trapezius/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f2_Trapezius/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f2_Trapezius --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f2_Trapezius/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f3_Trapezius.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f3_Trapezius/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f3_Trapezius/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f3_Trapezius --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f3_Trapezius/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f4_Trapezius.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f4_Trapezius/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f4_Trapezius/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f4_Trapezius --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f4_Trapezius/ann_dir/test

############## FSHD - Vastus_lateralis ###########################
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f0_Vastus_lateralis.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f0_Vastus_lateralis/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f0_Vastus_lateralis/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f0_Vastus_lateralis --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f0_Vastus_lateralis/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f1_Vastus_lateralis.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f1_Vastus_lateralis/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f1_Vastus_lateralis/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f1_Vastus_lateralis --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f1_Vastus_lateralis/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f2_Vastus_lateralis.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f2_Vastus_lateralis/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f2_Vastus_lateralis/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f2_Vastus_lateralis --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f2_Vastus_lateralis/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f3_Vastus_lateralis.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f3_Vastus_lateralis/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f3_Vastus_lateralis/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f3_Vastus_lateralis --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f3_Vastus_lateralis/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f4_Vastus_lateralis.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f4_Vastus_lateralis/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f4_Vastus_lateralis/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f4_Vastus_lateralis --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f4_Vastus_lateralis/ann_dir/test

############## FSHD - Zygomaticus ###########################
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f0_Zygomaticus.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f0_Zygomaticus/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f0_Zygomaticus/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f0_Zygomaticus --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f0_Zygomaticus/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f1_Zygomaticus.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f1_Zygomaticus/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f1_Zygomaticus/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f1_Zygomaticus --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f1_Zygomaticus/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f2_Zygomaticus.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f2_Zygomaticus/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f2_Zygomaticus/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f2_Zygomaticus --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f2_Zygomaticus/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f3_Zygomaticus.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f3_Zygomaticus/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f3_Zygomaticus/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f3_Zygomaticus --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f3_Zygomaticus/ann_dir/test
python tools/local_inference.py /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/configs/FSHD_experiments/FSHD_config_SWIN_f4_Zygomaticus.py --checkpoint /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f4_Zygomaticus/iter_20000.pth --img_folder /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f4_Zygomaticus/img_dir/test --out_results /home/francesco/Desktop/POLI/RADBOUD/RESULTS/FSHD/FSHD_KNET_SWIN_f4_Zygomaticus --ground_truth /home/francesco/Desktop/POLI/RADBOUD/CODE/mmsegmentation/data/FSHD_v3_f4_Zygomaticus/ann_dir/test
